Repository meetncode/meetncode, pull requests merged in 2019-07, with the labels that each got.

#18 Feature/register
  client/package.json
  client/src/components/Footer/Footer.js
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/LoginFormContainer.js
  client/src/components/SignUpForm/SignUpForm.js
  client/src/components/SignUpForm/SignupFormContainer.js
Labels: enhancement, wip

#20 revert material-ui packages to updated version
  client/package.json
  client/yarn.lock
Labels: bug, review first

#24 Change Login to be a mutation
  server/User/UserResolvers.js
  server/User/UserTypes.js
Labels: review me
